complete -F _optcomplete raxmon-views-overview
complete -F _optcomplete raxmon-monitoring-zones-list
complete -F _optcomplete raxmon-monitoring-zones-create
complete -F _optcomplete raxmon-monitoring-zones-update
complete -F _optcomplete raxmon-monitoring-zones-delete
complete -F _optcomplete raxmon-check-types-list
complete -F _optcomplete raxmon-limits-list
complete -F _optcomplete raxmon-checks-enable
complete -F _optcomplete raxmon-audits-list
complete -F _optcomplete raxmon-notifications-delete
complete -F _optcomplete raxmon-notifications-list
complete -F _optcomplete raxmon-alarms-validate-criteria
complete -F _optcomplete raxmon-notification-plans-create
complete -F _optcomplete raxmon-entities-list
complete -F _optcomplete raxmon-notifications-update
complete -F _optcomplete raxmon-entities-delete
complete -F _optcomplete raxmon-notification-plans-list
complete -F _optcomplete raxmon-alarms-delete
complete -F _optcomplete raxmon-alarms-test
complete -F _optcomplete raxmon-entities-create
complete -F _optcomplete raxmon-notifications-create
complete -F _optcomplete raxmon-notification-plans-update
complete -F _optcomplete raxmon-checks-update
complete -F _optcomplete raxmon-checks-create
complete -F _optcomplete raxmon-checks-disable
complete -F _optcomplete raxmon-notification-plans-delete
complete -F _optcomplete raxmon-checks-test
complete -F _optcomplete raxmon-notifications-test-existing
complete -F _optcomplete raxmon-notifications-test
complete -F _optcomplete raxmon-notification-types-list
complete -F _optcomplete raxmon-alarms-update
complete -F _optcomplete raxmon-entities-update
complete -F _optcomplete raxmon-checks-list
complete -F _optcomplete raxmon-alarm-changelog-list
complete -F _optcomplete raxmon-alarms-list
complete -F _optcomplete raxmon-checks-delete
complete -F _optcomplete raxmon-alarms-create
complete -F _optcomplete raxmon