#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from raxmon_cli.common import run_action

OPTIONS = [
    [['--entity-id'], {'dest': 'entity_id', 'help': 'Entity ID'}],
    [['--type'], {'dest': 'type', 'help': 'Agent Check Type (agent.memory, ' +
      'agent.filesystem, agent.disk, agent.plugin)'}],
]

REQUIRED_OPTIONS = ['entity_id', 'type']

def callback(driver, options, args, callback):
    result = driver.get_entity_agent_targets(entity_id=options.entity_id,
        check_type=options.type)
    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'entity_agent_targets', 'view', callback)
