#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

try:
    import simplejson as json
except ImportError:
    import json

from raxmon_cli.common import run_action
from raxmon_cli.utils import read_json_from_file

OPTIONS = [
    [['--entity-id'], {'dest': 'entity_id', 'help': 'Parent Entity ID'}],
    [['--criteria'], {'dest': 'criteria', 'help': 'Alarm criteria'}],
    [['--check-data'], {'dest': 'check_data', 'help': 'Path to the file ' +
                        'containing check data'}]
]

REQUIRED_OPTIONS = ['entity_id']

def callback(driver, options, args, callback):
    en = driver.get_entity(entity_id=options.entity_id)

    if options.check_data:
        options.check_data = read_json_from_file(options.check_data)
        options.check_data = json.loads(options.check_data)

    result = driver.test_alarm(entity=en, criteria=options.criteria,
                               check_data=options.check_data)
    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'alarms', 'test', callback)
