#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from raxmon_cli.common import run_action

OPTIONS = [
    [['--agent-id'], {'dest': 'agent_id', 'help': 'Agent ID'}],
    [['--type'], {'dest': 'type', 'help': 'Info Type (memory, cpus, ' +
      'network_interfaces, system, disks, filesystems, processes)'}],
]

REQUIRED_OPTIONS = ['agent_id', 'type']

def callback(driver, options, args, callback):
    result = driver.get_agent_host_info(agent_id=options.agent_id,
        info_type=options.type)
    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'agent_host_info', 'view', callback)
