#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from raxmon_cli.common import run_action
from raxmon_cli.utils import str_to_dict, instance_to_dict

OPTIONS = [
    [['--id'], {'dest': 'id', 'help': 'Notification id'}],
    [['--label'], {'dest': 'label', 'help': 'Notification label'}],
    [['--type'], {'dest': 'type', 'help': 'Notification type'}],
    [['--details'], {'dest': 'details', 'help': 'Notification details'}],
]

REQUIRED_OPTIONS = ['id']

def callback(driver, options, args, callback):
    options.details = str_to_dict(options.details)
    no = driver.get_notification(notification_id=options.id)

    data = instance_to_dict(options, ['label', 'type', 'details'], False)
    result = driver.update_notification(notification=no, data=data,
                                        who=options.who,
                                        why=options.why)

    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'notifications', 'update', callback)
