#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import optparse

from raxmon_cli.common import run_action
from raxmon_cli.utils import instance_to_dict

OPTIONS = [
    [['--id'], {'dest': 'id', 'help': 'Zone id'}],
    [['--label'], {'dest': 'label', 'help': 'Zone label'}],
    [['--maximum_checks'], {'dest': 'maximum_checks', 'help': 'Maximum checks allowed for the zone'}],
    [['--maximum_agents'], {'dest': 'maximum_agents', 'help': 'Maximum pollers allowed in the zone'}]
]

REQUIRED_OPTIONS = ['id']

def callback(driver, options, args, callback):
    pz = driver.get_monitoring_zone(monitoring_zone_id=options.id)

    data = instance_to_dict(options, ['label', 'maximum_checks', 'maximum_agents'], False)
    result = driver.update_monitoring_zone(monitoring_zone=pz, data=data,
                                  who=options.who,
                                  why=options.why)

    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'monitoring_zones', 'update', callback)